-- 1. Create Schema Owner
CREATE USER LIFELINE_CONNECT IDENTIFIED BY "LifeLine2026"
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO LIFELINE_CONNECT;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER, CREATE SEQUENCE TO LIFELINE_CONNECT;

-- 2. Create Roles
CREATE ROLE RL_LIFELINE_ADMIN;
CREATE ROLE RL_CLINICAL_STAFF;
CREATE ROLE RL_HOSPITAL_COORDINATOR;

-- 3. Create users
CREATE USER staff_user IDENTIFIED BY "Staff#2026";
CREATE USER hospital_user IDENTIFIED BY "Hosp#2026";

GRANT CONNECT TO staff_user, hospital_user;
GRANT RL_CLINICAL_STAFF TO staff_user;
GRANT RL_HOSPITAL_COORDINATOR TO hospital_user;




-- Unlock account

ALTER SESSION SET CONTAINER = XEPDB1;

-- 1. Unlock the account and reset the password cleanly
ALTER USER LIFELINE_CONNECT IDENTIFIED BY LifeLine2026 ACCOUNT UNLOCK;

-- 2. Prevent the account from locking again during development
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;