ALTER SESSION SET CONTAINER = XEPDB1;


-- 1. SCHEMA OWNER CREATION & PRIVILEGES

CREATE USER LIFELINE_CONNECT IDENTIFIED BY "LifeLine2026"
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO LIFELINE_CONNECT;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER, CREATE SEQUENCE, CREATE SYNONYM TO LIFELINE_CONNECT;

-- Account unlock & security profile settings for development
ALTER USER LIFELINE_CONNECT IDENTIFIED BY LifeLine2026 ACCOUNT UNLOCK;
ALTER PROFILE DEFAULT LIMIT FAILED_LOGIN_ATTEMPTS UNLIMITED;



-- 2. ROLE-BASED ACCESS CONTROL (RBAC) DEFINITION

CREATE ROLE RL_LIFELINE_ADMIN;
CREATE ROLE RL_CLINICAL_STAFF;
CREATE ROLE RL_HOSPITAL_COORDINATOR;


-- 3. OBJECT-LEVEL PRIVILEGE GRANTS TO ROLES


-- A. RL_CLINICAL_STAFF (Phlebotomists, Medical Screening Officers)
-- Permitted to register donors, conduct health exams, log donations, and manage blood units
GRANT SELECT, INSERT, UPDATE ON LIFELINE_CONNECT.DONOR TO RL_CLINICAL_STAFF;
GRANT SELECT, INSERT, UPDATE ON LIFELINE_CONNECT.DONOR_HEALTH TO RL_CLINICAL_STAFF;
GRANT SELECT, INSERT ON LIFELINE_CONNECT.DONATION TO RL_CLINICAL_STAFF;
GRANT SELECT, INSERT, UPDATE ON LIFELINE_CONNECT.BLOOD_UNIT TO RL_CLINICAL_STAFF;

-- Read-only visibility for camps, venues, staff, and volunteers
GRANT SELECT ON LIFELINE_CONNECT.CAMP TO RL_CLINICAL_STAFF;
GRANT SELECT ON LIFELINE_CONNECT.VENUE TO RL_CLINICAL_STAFF;
GRANT SELECT ON LIFELINE_CONNECT.CAMP_STAFF TO RL_CLINICAL_STAFF;
GRANT SELECT ON LIFELINE_CONNECT.CAMP_VOLUNTEER TO RL_CLINICAL_STAFF;
GRANT SELECT ON LIFELINE_CONNECT.STAFF TO RL_CLINICAL_STAFF;
GRANT SELECT ON LIFELINE_CONNECT.VOLUNTEER TO RL_CLINICAL_STAFF;

-- Execute permission on business reports package
GRANT EXECUTE ON LIFELINE_CONNECT.LIFELINE_REPORTS_PKG TO RL_CLINICAL_STAFF;


-- B. RL_HOSPITAL_COORDINATOR (Hospital Blood Bank Representatives)
-- Permitted to submit emergency requisitions, specify line items, and view distribution status
GRANT SELECT, INSERT, UPDATE ON LIFELINE_CONNECT.BLOOD_REQUEST TO RL_HOSPITAL_COORDINATOR;
GRANT SELECT, INSERT, UPDATE ON LIFELINE_CONNECT.REQUEST_ITEM TO RL_HOSPITAL_COORDINATOR;
GRANT SELECT, INSERT ON LIFELINE_CONNECT.DISTRIBUTION TO RL_HOSPITAL_COORDINATOR;

-- Read-only visibility for inventory availability and hospital directories
GRANT SELECT ON LIFELINE_CONNECT.BLOOD_UNIT TO RL_HOSPITAL_COORDINATOR;
GRANT SELECT ON LIFELINE_CONNECT.HOSPITAL TO RL_HOSPITAL_COORDINATOR;
GRANT SELECT ON LIFELINE_CONNECT.STAFF TO RL_HOSPITAL_COORDINATOR;

-- Execute permission for hospital fulfillment reports
GRANT EXECUTE ON LIFELINE_CONNECT.LIFELINE_REPORTS_PKG TO RL_HOSPITAL_COORDINATOR;


-- C. RL_LIFELINE_ADMIN (System Administrators & Data Custodians)
-- Full administrative DML access across all 14 relational tables
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.VENUE TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.STAFF TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.VOLUNTEER TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.CAMP TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.CAMP_STAFF TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.CAMP_VOLUNTEER TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.DONOR TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.DONOR_HEALTH TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.DONATION TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.BLOOD_UNIT TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.HOSPITAL TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.BLOOD_REQUEST TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.REQUEST_ITEM TO RL_LIFELINE_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON LIFELINE_CONNECT.DISTRIBUTION TO RL_LIFELINE_ADMIN;

GRANT EXECUTE ON LIFELINE_CONNECT.LIFELINE_REPORTS_PKG TO RL_LIFELINE_ADMIN;


-- 4. APPLICATION USERS & ROLE ASSIGNMENTS

CREATE USER admin_user IDENTIFIED BY "Admin#2026";
CREATE USER staff_user IDENTIFIED BY "Staff#2026";
CREATE USER hospital_user IDENTIFIED BY "Hosp#2026";

-- Grant basic session connection privilege
GRANT CONNECT TO admin_user, staff_user, hospital_user;
GRANT CREATE SESSION TO admin_user;
GRANT CREATE SESSION TO staff_user;
GRANT CREATE SESSION TO hospital_user;



-- Assign designated roles 
GRANT RL_LIFELINE_ADMIN TO admin_user;
GRANT RL_CLINICAL_STAFF TO staff_user;
GRANT RL_HOSPITAL_COORDINATOR TO hospital_user;

-- Set default roles for session 
ALTER USER admin_user DEFAULT ROLE RL_LIFELINE_ADMIN;
ALTER USER staff_user DEFAULT ROLE RL_CLINICAL_STAFF;
ALTER USER hospital_user DEFAULT ROLE RL_HOSPITAL_COORDINATOR;

COMMIT;